/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TickerRouteRouteImport } from './routes/$ticker/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TickerIndexRouteImport } from './routes/$ticker/index'
import { Route as TickerStockSplitsIndexRouteImport } from './routes/$ticker/stock-splits/index'
import { Route as TickerFinancialsStandardizedIndexRouteImport } from './routes/$ticker/financials-standardized/index'
import { Route as TickerFinancialsAsReportedIndexRouteImport } from './routes/$ticker/financials-as-reported/index'
import { Route as TickerFilingsIndexRouteImport } from './routes/$ticker/filings/index'
import { Route as TickerDividendsIndexRouteImport } from './routes/$ticker/dividends/index'

const TickerRouteRoute = TickerRouteRouteImport.update({
  id: '/$ticker',
  path: '/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerIndexRoute = TickerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TickerRouteRoute,
} as any)
const TickerStockSplitsIndexRoute = TickerStockSplitsIndexRouteImport.update({
  id: '/stock-splits/',
  path: '/stock-splits/',
  getParentRoute: () => TickerRouteRoute,
} as any)
const TickerFinancialsStandardizedIndexRoute =
  TickerFinancialsStandardizedIndexRouteImport.update({
    id: '/financials-standardized/',
    path: '/financials-standardized/',
    getParentRoute: () => TickerRouteRoute,
  } as any)
const TickerFinancialsAsReportedIndexRoute =
  TickerFinancialsAsReportedIndexRouteImport.update({
    id: '/financials-as-reported/',
    path: '/financials-as-reported/',
    getParentRoute: () => TickerRouteRoute,
  } as any)
const TickerFilingsIndexRoute = TickerFilingsIndexRouteImport.update({
  id: '/filings/',
  path: '/filings/',
  getParentRoute: () => TickerRouteRoute,
} as any)
const TickerDividendsIndexRoute = TickerDividendsIndexRouteImport.update({
  id: '/dividends/',
  path: '/dividends/',
  getParentRoute: () => TickerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRouteRouteWithChildren
  '/$ticker/': typeof TickerIndexRoute
  '/$ticker/dividends': typeof TickerDividendsIndexRoute
  '/$ticker/filings': typeof TickerFilingsIndexRoute
  '/$ticker/financials-as-reported': typeof TickerFinancialsAsReportedIndexRoute
  '/$ticker/financials-standardized': typeof TickerFinancialsStandardizedIndexRoute
  '/$ticker/stock-splits': typeof TickerStockSplitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$ticker': typeof TickerIndexRoute
  '/$ticker/dividends': typeof TickerDividendsIndexRoute
  '/$ticker/filings': typeof TickerFilingsIndexRoute
  '/$ticker/financials-as-reported': typeof TickerFinancialsAsReportedIndexRoute
  '/$ticker/financials-standardized': typeof TickerFinancialsStandardizedIndexRoute
  '/$ticker/stock-splits': typeof TickerStockSplitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRouteRouteWithChildren
  '/$ticker/': typeof TickerIndexRoute
  '/$ticker/dividends/': typeof TickerDividendsIndexRoute
  '/$ticker/filings/': typeof TickerFilingsIndexRoute
  '/$ticker/financials-as-reported/': typeof TickerFinancialsAsReportedIndexRoute
  '/$ticker/financials-standardized/': typeof TickerFinancialsStandardizedIndexRoute
  '/$ticker/stock-splits/': typeof TickerStockSplitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$ticker'
    | '/$ticker/'
    | '/$ticker/dividends'
    | '/$ticker/filings'
    | '/$ticker/financials-as-reported'
    | '/$ticker/financials-standardized'
    | '/$ticker/stock-splits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$ticker'
    | '/$ticker/dividends'
    | '/$ticker/filings'
    | '/$ticker/financials-as-reported'
    | '/$ticker/financials-standardized'
    | '/$ticker/stock-splits'
  id:
    | '__root__'
    | '/'
    | '/$ticker'
    | '/$ticker/'
    | '/$ticker/dividends/'
    | '/$ticker/filings/'
    | '/$ticker/financials-as-reported/'
    | '/$ticker/financials-standardized/'
    | '/$ticker/stock-splits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TickerRouteRoute: typeof TickerRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$ticker': {
      id: '/$ticker'
      path: '/$ticker'
      fullPath: '/$ticker'
      preLoaderRoute: typeof TickerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$ticker/': {
      id: '/$ticker/'
      path: '/'
      fullPath: '/$ticker/'
      preLoaderRoute: typeof TickerIndexRouteImport
      parentRoute: typeof TickerRouteRoute
    }
    '/$ticker/stock-splits/': {
      id: '/$ticker/stock-splits/'
      path: '/stock-splits'
      fullPath: '/$ticker/stock-splits'
      preLoaderRoute: typeof TickerStockSplitsIndexRouteImport
      parentRoute: typeof TickerRouteRoute
    }
    '/$ticker/financials-standardized/': {
      id: '/$ticker/financials-standardized/'
      path: '/financials-standardized'
      fullPath: '/$ticker/financials-standardized'
      preLoaderRoute: typeof TickerFinancialsStandardizedIndexRouteImport
      parentRoute: typeof TickerRouteRoute
    }
    '/$ticker/financials-as-reported/': {
      id: '/$ticker/financials-as-reported/'
      path: '/financials-as-reported'
      fullPath: '/$ticker/financials-as-reported'
      preLoaderRoute: typeof TickerFinancialsAsReportedIndexRouteImport
      parentRoute: typeof TickerRouteRoute
    }
    '/$ticker/filings/': {
      id: '/$ticker/filings/'
      path: '/filings'
      fullPath: '/$ticker/filings'
      preLoaderRoute: typeof TickerFilingsIndexRouteImport
      parentRoute: typeof TickerRouteRoute
    }
    '/$ticker/dividends/': {
      id: '/$ticker/dividends/'
      path: '/dividends'
      fullPath: '/$ticker/dividends'
      preLoaderRoute: typeof TickerDividendsIndexRouteImport
      parentRoute: typeof TickerRouteRoute
    }
  }
}

interface TickerRouteRouteChildren {
  TickerIndexRoute: typeof TickerIndexRoute
  TickerDividendsIndexRoute: typeof TickerDividendsIndexRoute
  TickerFilingsIndexRoute: typeof TickerFilingsIndexRoute
  TickerFinancialsAsReportedIndexRoute: typeof TickerFinancialsAsReportedIndexRoute
  TickerFinancialsStandardizedIndexRoute: typeof TickerFinancialsStandardizedIndexRoute
  TickerStockSplitsIndexRoute: typeof TickerStockSplitsIndexRoute
}

const TickerRouteRouteChildren: TickerRouteRouteChildren = {
  TickerIndexRoute: TickerIndexRoute,
  TickerDividendsIndexRoute: TickerDividendsIndexRoute,
  TickerFilingsIndexRoute: TickerFilingsIndexRoute,
  TickerFinancialsAsReportedIndexRoute: TickerFinancialsAsReportedIndexRoute,
  TickerFinancialsStandardizedIndexRoute:
    TickerFinancialsStandardizedIndexRoute,
  TickerStockSplitsIndexRoute: TickerStockSplitsIndexRoute,
}

const TickerRouteRouteWithChildren = TickerRouteRoute._addFileChildren(
  TickerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TickerRouteRoute: TickerRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
