/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TickerRouteRouteImport } from './routes/$ticker/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TickerIndexRouteImport } from './routes/$ticker/index'
import { Route as TickerFinancialsStandardizedRouteImport } from './routes/$ticker/financials-standardized'
import { Route as TickerFilingsIndexRouteImport } from './routes/$ticker/filings/index'

const TickerRouteRoute = TickerRouteRouteImport.update({
  id: '/$ticker',
  path: '/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerIndexRoute = TickerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TickerRouteRoute,
} as any)
const TickerFinancialsStandardizedRoute =
  TickerFinancialsStandardizedRouteImport.update({
    id: '/financials-standardized',
    path: '/financials-standardized',
    getParentRoute: () => TickerRouteRoute,
  } as any)
const TickerFilingsIndexRoute = TickerFilingsIndexRouteImport.update({
  id: '/filings/',
  path: '/filings/',
  getParentRoute: () => TickerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRouteRouteWithChildren
  '/$ticker/financials-standardized': typeof TickerFinancialsStandardizedRoute
  '/$ticker/': typeof TickerIndexRoute
  '/$ticker/filings': typeof TickerFilingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$ticker/financials-standardized': typeof TickerFinancialsStandardizedRoute
  '/$ticker': typeof TickerIndexRoute
  '/$ticker/filings': typeof TickerFilingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRouteRouteWithChildren
  '/$ticker/financials-standardized': typeof TickerFinancialsStandardizedRoute
  '/$ticker/': typeof TickerIndexRoute
  '/$ticker/filings/': typeof TickerFilingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$ticker'
    | '/$ticker/financials-standardized'
    | '/$ticker/'
    | '/$ticker/filings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$ticker/financials-standardized' | '/$ticker' | '/$ticker/filings'
  id:
    | '__root__'
    | '/'
    | '/$ticker'
    | '/$ticker/financials-standardized'
    | '/$ticker/'
    | '/$ticker/filings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TickerRouteRoute: typeof TickerRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$ticker': {
      id: '/$ticker'
      path: '/$ticker'
      fullPath: '/$ticker'
      preLoaderRoute: typeof TickerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$ticker/': {
      id: '/$ticker/'
      path: '/'
      fullPath: '/$ticker/'
      preLoaderRoute: typeof TickerIndexRouteImport
      parentRoute: typeof TickerRouteRoute
    }
    '/$ticker/financials-standardized': {
      id: '/$ticker/financials-standardized'
      path: '/financials-standardized'
      fullPath: '/$ticker/financials-standardized'
      preLoaderRoute: typeof TickerFinancialsStandardizedRouteImport
      parentRoute: typeof TickerRouteRoute
    }
    '/$ticker/filings/': {
      id: '/$ticker/filings/'
      path: '/filings'
      fullPath: '/$ticker/filings'
      preLoaderRoute: typeof TickerFilingsIndexRouteImport
      parentRoute: typeof TickerRouteRoute
    }
  }
}

interface TickerRouteRouteChildren {
  TickerFinancialsStandardizedRoute: typeof TickerFinancialsStandardizedRoute
  TickerIndexRoute: typeof TickerIndexRoute
  TickerFilingsIndexRoute: typeof TickerFilingsIndexRoute
}

const TickerRouteRouteChildren: TickerRouteRouteChildren = {
  TickerFinancialsStandardizedRoute: TickerFinancialsStandardizedRoute,
  TickerIndexRoute: TickerIndexRoute,
  TickerFilingsIndexRoute: TickerFilingsIndexRoute,
}

const TickerRouteRouteWithChildren = TickerRouteRoute._addFileChildren(
  TickerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TickerRouteRoute: TickerRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
